### ISSUE TITLE
Follow semver rules?

### ISSUE THREAD

**Issue by XVincentX** [refractproject/minim#81]
Don't be afraid to start with 1.0.0 and bump to 2.0.0 if things changes.
You will save our lives: imagine us when seeing 0.10 and 0.11, consider it as a minor release and then you realise that there is a breaking change behind that.

**Comment by smizell** [comment]
@XVincentX Totally agree. I think we are actually close to being ready to do 1.0.0. I'll work on a new roadmap to get us there soon.

Please continue to push if we don't do it soon :)

**Comment by XVincentX** [comment]
Great, thanks.
By the way, in my opinion, if it's public, then it **MUST** follow the semver rules. That means: 1.0.0

**Comment by smizell** [comment]
@XVincentX I mostly agree here. I like to think of pre-1.0.0 as a stage where you're getting it to a stable release, because OSS is inherently public even before things are stable. Before 1.0.0, use at your own risk! But now we are close to having a stable API (and we may be there). So to me, 1.0.0 says this is our first stable API and we will be very careful with our changes, even non-breaking changes.

**Comment by smizell** [comment]
Closing this in favor of #83

**Comment by pksunkara** [comment]
@XVincentX From Semver rules,

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

So, we are still following server rules.
